CREATE DATABASE MONAPPECOLE;
GO

USE MONAPPECOLE;
GO

CREATE TABLE USERROLE (
    ROLEID INT PRIMARY KEY,
    ROLENAME VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO USERROLE VALUES
(0, 'Super Admin'),
(1, 'Admin'),
(2, 'User');

CREATE TABLE STATUTPAIEMENT (
    STATUTID INT PRIMARY KEY,
    STATUTLABEL VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO STATUTPAIEMENT VALUES
(1, 'Payé'),
(2, 'Non payé');

CREATE TABLE USERS (
    IDUSER INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME NVARCHAR(100) NOT NULL UNIQUE,
    NOM NVARCHAR(100),
    PRENOM NVARCHAR(100),
    PWD NVARCHAR(255) NOT NULL,
    EMAIL NVARCHAR(255),
    DATECREATION DATETIME DEFAULT GETDATE(),
    ACTIVE BIT NOT NULL DEFAULT 1,  -- colonne ACTIVE ajoutée, true par défaut
    ROLEID INT NOT NULL,
    SESSION_TOKEN NVARCHAR(100),
    LAST_LOGIN DATETIME DEFAULT GETDATE(),
    LAST_PC NVARCHAR(100),

    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES USERROLE(ROLEID)
);

INSERT INTO USERS (USERNAME, NOM, PRENOM, PWD, EMAIL, ROLEID)
VALUES (
    'superadmin',
    'Dupont',
    'Jean',
    '0',
    'j.dupont@example.com',
    0
);

CREATE TABLE ELEVES (
    IDELEVES INT IDENTITY(1,1) PRIMARY KEY,
    MATRICULE NVARCHAR(50) NOT NULL UNIQUE,
    NOM NVARCHAR(255) NULL,
    PRENOM NVARCHAR(255) NULL,
    BIRTHDAY DATE NULL,
    SEXE NVARCHAR(10) NULL,     
    CLASSE NVARCHAR(50) NOT NULL,
    NOMPERE NVARCHAR(255) NULL,
    NOMMERE NVARCHAR(255) NULL,
    CONTACT NVARCHAR(50) NULL,
    ADRESSE NVARCHAR(255) NULL,
    PATH NVARCHAR(255) NULL
);


CREATE TABLE CLASSES (
    IDCLASSE INT IDENTITY(1,1) PRIMARY KEY,
    LABEL NVARCHAR(255) NULL
);

INSERT INTO CLASSES (LABEL)
VALUES (
    '6ème'
);

CREATE TABLE MATIERES (
    IDMATIERE INT IDENTITY(1,1) PRIMARY KEY,
    LABEL NVARCHAR(255) NULL
);

INSERT INTO MATIERES (LABEL)
VALUES (
    'Mathématiques'
);

CREATE PROCEDURE BackupAndGetPath
    @BackupPath NVARCHAR(300) OUTPUT
AS
BEGIN
    DECLARE @FileName NVARCHAR(300)

    SET @FileName = 'C:\Backups\MaBase_' 
        + CONVERT(VARCHAR, GETDATE(), 112) 
        + '_' + REPLACE(CONVERT(VARCHAR, GETDATE(), 108), ':', '') 
        + '.bak'

    BACKUP DATABASE MaBase
    TO DISK = @FileName
    WITH INIT, COMPRESSION

    SET @BackupPath = @FileName
END
